image: Visual Studio 2022

init:
  - ps: net user appveyor Password123! /add
  - ps: net localgroup administrators appveyor /add
  - ps: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
  - ps: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

install:
  - choco install googlechrome -y
  - choco install firefox -y

build_script:
  - ps: Start-Process cmd "/c ping -t localhost" -WindowStyle Hidden
